apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: online-boutique

resources:
  - https://github.com/GoogleCloudPlatform/microservices-demo//kustomize?ref=5b3a712ab85ccb8f6f7cd5b720d36ba9a8d041eb
  - otel-collector.yaml

configMapGenerator:
  - name: otel-collector-config
    files:
      - collector.yaml=otel-collector-config.yaml

images:
  - name: redis
    newName: docker.io/library/redis
    digest: sha256:becdda6c7f4b3fb42e42fd7f120bbf5c54c4caaaf16f26da24e4563d2c1f0576

labels:
  - pairs:
      app.kubernetes.io/part-of: online-boutique
      kyunghoon02.github.io/target-version: v0.10.6
    includeSelectors: false

patches:
  - path: patches/checkoutservice-otel.yaml
  - path: patches/currencyservice-otel.yaml
  - path: patches/emailservice-otel.yaml
  - path: patches/frontend-otel.yaml
  - path: patches/paymentservice-otel.yaml
  - path: patches/productcatalogservice-otel.yaml
  - path: patches/recommendationservice-otel.yaml
  - target:
      group: ""
      version: v1
      kind: Service
      name: frontend-external
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: frontend-external
      $patch: delete
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: loadgenerator
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: loadgenerator
      $patch: delete
  - target:
      group: ""
      version: v1
      kind: ServiceAccount
      name: loadgenerator
    patch: |-
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: loadgenerator
      $patch: delete
