apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: observability
spec:
  type: NodePort
  ports:
    - name: http
      port: 3200
      targetPort: http
      nodePort: 30320
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
      nodePort: 30317
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
      nodePort: 30318
