"""Cloud-neutral core for the Incident Response and Agent RCA Platform."""

from .errors import ContractViolation, InvalidAlert, InvalidTransition
from .collectors import CollectorOrchestrator, CollectorSpec, IncidentCollectionService
from .deterministic import DeterministicDecision, DeterministicRCAEngine
from .evidence import (
    CollectionRequest,
    EvidenceBuilder,
    EvidenceDraft,
    EvidenceWindow,
    ProviderBatch,
    ResourceScope,
    verify_evidence_content_hash,
)
from .incidents import (
    AlertmanagerIngestionService,
    AlertmanagerNormalizer,
    IngestionResult,
)
from .http_receiver import (
    AlertmanagerHTTPReceiver,
    AlertmanagerWebhookWSGI,
    HTTPResponse,
    ReceiverConfig,
)
from .fast_path import FastPathRun, IncidentFastPathService
from .repository import InMemoryIncidentRepository
from .postgresql import PostgreSQLIncidentRepository, apply_migrations
from .providers import (
    KubernetesHTTPAPI,
    KubernetesResourceSpec,
    KubernetesStateProvider,
    PrometheusHTTPAPI,
    PrometheusMetricProvider,
    PrometheusQuerySpec,
)
from .reporting import FastPathArtifacts, FastPathReportBuilder, render_markdown
from .stategraph import (
    EntityIdentity,
    EntityLookup,
    GraphLocalizer,
    GraphProjection,
    InMemoryStateGraphRepository,
    InvestigationScope,
    StateGraphRepository,
    stable_graph_id,
    state_content_hash,
    validate_graph_record,
)
from .resolution import (
    EntityResolutionCandidate,
    EntityResolutionRequest,
    EntityResolutionResult,
    InvestigationScopeFactory,
    ResolvedIncidentLocalizationRun,
    ResolvedIncidentLocalizationService,
    ServiceToEntityResolver,
)
from .localization import (
    AdaptiveLocalizationRound,
    AdaptiveLocalizationRun,
    AdaptiveScopeController,
    AdaptiveScopePolicy,
    EvidenceProjector,
    IncidentLocalizationRun,
    IncidentLocalizationService,
    LocalizationAssessment,
    LocalizationAssessor,
)
from .krca import (
    APIEdgeSignal,
    APIRef,
    KRCACandidate,
    KRCADrilldownLocalizer,
    KRCADrilldownPolicy,
    KRCADrilldownRun,
    KRCADrilldownScorer,
    KRCAScoredEdge,
)
from .projectors import KubernetesEvidenceProjector

__all__ = [
    "AlertmanagerIngestionService",
    "AlertmanagerHTTPReceiver",
    "AlertmanagerNormalizer",
    "AlertmanagerWebhookWSGI",
    "APIEdgeSignal",
    "APIRef",
    "AdaptiveLocalizationRound",
    "AdaptiveLocalizationRun",
    "AdaptiveScopeController",
    "AdaptiveScopePolicy",
    "CollectionRequest",
    "CollectorOrchestrator",
    "CollectorSpec",
    "ContractViolation",
    "DeterministicDecision",
    "DeterministicRCAEngine",
    "EvidenceBuilder",
    "EvidenceDraft",
    "EvidenceProjector",
    "EvidenceWindow",
    "EntityIdentity",
    "EntityLookup",
    "EntityResolutionCandidate",
    "EntityResolutionRequest",
    "EntityResolutionResult",
    "FastPathArtifacts",
    "FastPathReportBuilder",
    "FastPathRun",
    "GraphLocalizer",
    "GraphProjection",
    "InMemoryStateGraphRepository",
    "InMemoryIncidentRepository",
    "IncidentCollectionService",
    "IncidentFastPathService",
    "IncidentLocalizationRun",
    "IncidentLocalizationService",
    "IngestionResult",
    "HTTPResponse",
    "InvalidAlert",
    "InvalidTransition",
    "InvestigationScope",
    "InvestigationScopeFactory",
    "KubernetesHTTPAPI",
    "KubernetesEvidenceProjector",
    "KubernetesResourceSpec",
    "KubernetesStateProvider",
    "KRCACandidate",
    "KRCADrilldownLocalizer",
    "KRCADrilldownPolicy",
    "KRCADrilldownRun",
    "KRCADrilldownScorer",
    "KRCAScoredEdge",
    "LocalizationAssessment",
    "LocalizationAssessor",
    "ProviderBatch",
    "PostgreSQLIncidentRepository",
    "PrometheusHTTPAPI",
    "PrometheusMetricProvider",
    "PrometheusQuerySpec",
    "ResourceScope",
    "ResolvedIncidentLocalizationRun",
    "ResolvedIncidentLocalizationService",
    "ReceiverConfig",
    "StateGraphRepository",
    "ServiceToEntityResolver",
    "apply_migrations",
    "render_markdown",
    "stable_graph_id",
    "state_content_hash",
    "validate_graph_record",
    "verify_evidence_content_hash",
]
